# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa462c335f90e4f5ccb9bf0a2c0c7ffb2610eb0e2f2ce51ad6de6cbad5a7b27020fe1856e925886eec3fc1ca6fda6112db6c0999e1dad35db10cf2049fbb6daa

test:
  secret_key_base: 30754402658f9077d2f218c5ec90327e1aeeabf76f432456b56d22273a3ea433cc114599d1ff738b913892290d7feeb8f702e01bc2dc6877d46304cbf18c852f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
